[package]
name = "poe2openai"
version = "0.2.5"
edition = "2024"
publish = ["crates-io"]
authors = ["Jerome Leong <jeromeleong1998@gmail.com>"]
description = "Poe API to OpenAI API"
repository = "https://github.com/jeromeleong/poe2openai"
license = "MIT"
keywords = ["poeapi", "openai","ai"]

[dependencies]
poe_api_process = "0.1.5"
tokio = { version = "1.44.1", features = ["full"] }
futures-util = "0.3.31"
salvo = { version = "0.77.0", features = ["basic-auth","size-limiter","serve-static","cors","compression"] }
serde = "1.0.219"
serde_json = "1.0.140"
chrono = "0.4.40"
nanoid = "0.4.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
askama = "0.12.1"
serde_yaml = "0.9.34"
dotenv = "0.15"
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", 
"migrate", "sqlite", "mysql", "postgres"] }
dotenvy = "0.15"
async-trait = "0.1.77"

